name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bash shell/install-dependencies.sh

      - name: Build with CMake
        run: bash shell/build.sh

      - name: Run tests with CTest
        run: bash shell/test.sh

  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bash shell/install-dependencies.sh

      - name: Run clang-format check
        run: bash shell/format.sh